// <auto-generated />
using System;
using MeGui.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeGui.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MeGui.Models.ChatSession", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentCheckpointOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CurrentRouteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.HasIndex("CurrentRouteId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("MeGui.Models.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Checkpoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageUrl = "https://placehold.co/600x400?text=Checkpoint+1+-+Plataforma+Se",
                            Instruction = "Você está na plataforma da estação Sé. Siga em direção à saída indicada pela placa 'Linha 1 - Azul, sentido Tucuruvi'. Suba a escada rolante à sua esquerda.",
                            Order = 1,
                            RouteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ImageUrl = "https://placehold.co/600x400?text=Checkpoint+2+-+Corredor",
                            Instruction = "Após subir a escada rolante, siga pelo corredor principal. Você verá uma banca de jornais à direita. Continue reto por aproximadamente 50 metros.",
                            Order = 2,
                            RouteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ImageUrl = "https://placehold.co/600x400?text=Checkpoint+3+-+Embarque",
                            Instruction = "Você chegou à plataforma da Linha 1 - Azul. Aguarde o trem no sentido Tucuruvi. Embarque e desça na próxima estação: Paraíso. De lá, faça a transferência para a Linha 2 - Verde sentido Vila Madalena.",
                            Order = 3,
                            RouteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ImageUrl = "https://placehold.co/600x400?text=Checkpoint+4+-+Paraiso",
                            Instruction = "Você está na estação Paraíso. Siga as placas indicando 'Linha 2 - Verde'. Desça a escada à direita e siga pelo corredor de transferência.",
                            Order = 4,
                            RouteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ImageUrl = "https://placehold.co/600x400?text=Checkpoint+5+-+Paulista",
                            Instruction = "Embarque no trem da Linha 2 - Verde sentido Vila Madalena. A próxima estação é a Paulista (Consolação). Você chegou ao seu destino! 🎉",
                            Order = 5,
                            RouteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("MeGui.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationStation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginStation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DestinationStation = "Paulista",
                            OriginStation = "Sé"
                        });
                });

            modelBuilder.Entity("MeGui.Models.ChatSession", b =>
                {
                    b.HasOne("MeGui.Models.Route", "CurrentRoute")
                        .WithMany()
                        .HasForeignKey("CurrentRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentRoute");
                });

            modelBuilder.Entity("MeGui.Models.Checkpoint", b =>
                {
                    b.HasOne("MeGui.Models.Route", "Route")
                        .WithMany("Checkpoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MeGui.Models.Route", b =>
                {
                    b.Navigation("Checkpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
